import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    // next-env.d.ts is generated by Next on every build; editing it is pointless.
    ignores: [
      ".next/**",
      "node_modules/**",
      "drizzle/**",
      "uploads/**",
      "public/**",
      "next-env.d.ts",
      // Vendored design mockups — third-party output, not our source.
      "design-mockups/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Wikimedia and upload images are served through our own proxy routes with
      // known dimensions; next/image adds no benefit and breaks the proxy URLs.
      "@next/next/no-img-element": "off",
    },
  },
];

export default config;
