import puppeteer from 'puppeteer';
const b=await puppeteer.launch({headless:'new',args:['--disable-gpu']});
const p=await b.newPage(); await p.setViewport({width:1400,height:1150});
await p.goto(process.argv[2],{waitUntil:'networkidle2',timeout:90000}).catch(()=>{});
await p.evaluate(async()=>{await Promise.all([...document.images].map(i=>i.complete?1:new Promise(r=>{i.onload=r;i.onerror=r;})));});
await new Promise(r=>setTimeout(r,3500));
console.log('page height:', await p.evaluate(()=>document.body.scrollHeight));
console.log('toggle:', await p.evaluate(()=>[...document.querySelectorAll('button[aria-pressed]')].map(b=>b.textContent.trim()).filter(t=>t.includes('view')).join(' | ')||'none'));
await p.screenshot({path:process.argv[3]});
await b.close();
