import type { SeedCountry } from "./types";

const india: SeedCountry = {
  code: "IN",
  name: "India",
  slug: "india",
  motif: "peacock",
  wikidataId: "Q668",
  emoji: "🇮🇳",
  regions: [
    { name: "Delhi", slug: "delhi", kind: "union territory", wikidataId: "Q1353" },
    { name: "Ladakh", slug: "ladakh", kind: "union territory", wikidataId: "Q200667" },
  { name: "Andhra Pradesh", slug: "andhra-pradesh", kind: "state", wikidataId: "Q1159" },
  { name: "Arunachal Pradesh", slug: "arunachal-pradesh", kind: "state", wikidataId: "Q1162" },
  { name: "Assam", slug: "assam", kind: "state", wikidataId: "Q1164" },
  { name: "Bihar", slug: "bihar", kind: "state", wikidataId: "Q1165" },
  { name: "Chhattisgarh", slug: "chhattisgarh", kind: "state", wikidataId: "Q1168" },
  { name: "Goa", slug: "goa", kind: "state", wikidataId: "Q1171" },
  { name: "Gujarat", slug: "gujarat", kind: "state", wikidataId: "Q1061" },
  { name: "Haryana", slug: "haryana", kind: "state", wikidataId: "Q1174" },
  { name: "Himachal Pradesh", slug: "himachal-pradesh", kind: "state", wikidataId: "Q1177" },
  { name: "Jharkhand", slug: "jharkhand", kind: "state", wikidataId: "Q1184" },
  { name: "Karnataka", slug: "karnataka", kind: "state", wikidataId: "Q1185" },
  { name: "Kerala", slug: "kerala", kind: "state", wikidataId: "Q1186" },
  { name: "Madhya Pradesh", slug: "madhya-pradesh", kind: "state", wikidataId: "Q1188" },
  { name: "Maharashtra", slug: "maharashtra", kind: "state", wikidataId: "Q1191" },
  { name: "Manipur", slug: "manipur", kind: "state", wikidataId: "Q1193" },
  { name: "Meghalaya", slug: "meghalaya", kind: "state", wikidataId: "Q1195" },
  { name: "Mizoram", slug: "mizoram", kind: "state", wikidataId: "Q1502" },
  { name: "Nagaland", slug: "nagaland", kind: "state", wikidataId: "Q1599" },
  { name: "Odisha", slug: "odisha", kind: "state", wikidataId: "Q22048" },
  { name: "Punjab", slug: "punjab", kind: "state", wikidataId: "Q22424" },
  { name: "Rajasthan", slug: "rajasthan", kind: "state", wikidataId: "Q1437" },
  { name: "Sikkim", slug: "sikkim", kind: "state", wikidataId: "Q1505" },
  { name: "Tamil Nadu", slug: "tamil-nadu", kind: "state", wikidataId: "Q1445" },
  { name: "Telangana", slug: "telangana", kind: "state", wikidataId: "Q677037" },
  { name: "Tripura", slug: "tripura", kind: "state", wikidataId: "Q1363" },
  { name: "Uttar Pradesh", slug: "uttar-pradesh", kind: "state", wikidataId: "Q1498" },
  { name: "Uttarakhand", slug: "uttarakhand", kind: "state", wikidataId: "Q1499" },
  { name: "West Bengal", slug: "west-bengal", kind: "state", wikidataId: "Q1356" },
  ],
  summary:
    "Mughal marble, painted palaces and food worth travelling for — India rewards the unhurried.",
  cities: [
    {
      name: "Kochi",
      slug: "kochi",
      region: "kerala",
      wikidataId: "Q1800",
      summary: "Spice-trade port where Chinese nets, Portuguese churches and Dutch houses share a shoreline.",
      lat: 9.9312,
      lng: 76.2673,
      places: [
        {
          name: "Fort Kochi",
          slug: "fort-kochi",
          wikidataId: "Q3595166",
          kind: "culture",
          summary: "Colonial quarter of godowns and cantilevered fishing nets, best walked at dusk.",
          lat: 9.9656,
          lng: 76.2425,
          visitMinutes: 180,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Monsoon runs June to September; winter is dry and walkable.",
          collectibles: [
            {
              name: "Kathakali performance ticket",
              slug: "kathakali-ticket",
              kind: "souvenir",
              description:
                "Stub from an evening Kathakali recital, with the make-up session beforehand.",
              whereToGet: "Kerala Kathakali Centre, River Road",
              cost: 400,
            },
          ],
        },
        {
          name: "Kerala backwaters",
          slug: "kerala-backwaters",
          activities: [
            {
              name: "Overnight houseboat",
              slug: "overnight-houseboat",
              summary: "Private boat through the canals, meals cooked aboard.",
              effort: "easy",
              minutes: 960,
              cost: 9000,
            },
            {
              name: "Shikara canoe, half day",
              slug: "shikara-canoe",
              summary: "Small punted canoe into the narrow canals a houseboat cannot enter.",
              effort: "easy",
              minutes: 240,
              cost: 1200,
              bestTime: "Late afternoon, for the light",
            },
          ],
          wikidataId: "Q666519",
          kind: "nature",
          summary: "Nine hundred kilometres of linked lagoons and canals behind the coast.",
          lat: 9.4981,
          lng: 76.3388,
          visitMinutes: 480,
          bestMonths: [11, 12, 1, 2, 3],
          seasonNote: "Houseboats run year-round but the water is calmest after the monsoon.",
        },
      ],
    },
    {
      name: "Munnar",
      slug: "munnar",
      region: "kerala",
      wikidataId: "Q1025124",
      summary: "Tea country in the Western Ghats — terraced slopes, mist and cardamom hills.",
      lat: 10.0889,
      lng: 77.0595,
      places: [
        {
          name: "Periyar National Park",
          slug: "periyar-national-park",
          wikidataId: "Q548153",
          kind: "nature",
          summary: "Tiger reserve around a lake, best seen from a dawn boat.",
          lat: 9.4622,
          lng: 77.2372,
          visitMinutes: 300,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote: "Animals come to the water in the dry months; leeches arrive with the rain.",
        },
      ],
    },
    {
      name: "Panaji",
      slug: "panaji",
      region: "goa",
      wikidataId: "Q214681",
      summary: "Portuguese-era capital of tiled roofs, balcões and a river that empties into the sea.",
      lat: 15.4909,
      lng: 73.8278,
      places: [
        {
          name: "Basilica of Bom Jesus",
          slug: "basilica-bom-jesus",
          wikidataId: "Q391123",
          kind: "culture",
          summary: "Baroque basilica in Old Goa holding the remains of St Francis Xavier.",
          lat: 15.5009,
          lng: 73.9116,
          visitMinutes: 90,
          bestMonths: [11, 12, 1, 2, 3],
          seasonNote: "Goa's monsoon is heavy; November to March is the dry stretch.",
        },
        {
          name: "Palolem Beach",
          slug: "palolem-beach",
          wikidataId: "Q2048357",
          kind: "nature",
          summary: "Crescent bay in south Goa, calmer than the northern beaches.",
          lat: 15.0100,
          lng: 74.0233,
          visitMinutes: 240,
          bestMonths: [11, 12, 1, 2, 3],
          seasonNote: "Shacks are dismantled for the monsoon and rebuilt each October.",
        },
      ],
    },
    {
      name: "Hampi",
      slug: "hampi",
      region: "karnataka",
      wikidataId: "Q26732",
      summary: "Ruined Vijayanagara capital scattered across a boulder landscape.",
      lat: 15.3350,
      lng: 76.4600,
      places: [
        {
          name: "Hampi monuments",
          slug: "hampi-monuments",
          activities: [
            {
              name: "Cycle the ruins",
              slug: "cycle-ruins",
              summary: "Hired bicycle between the temple groups across the boulder field.",
              effort: "moderate",
              minutes: 420,
              cost: 300,
            },
            {
              name: "Sacred centre on foot",
              slug: "sacred-centre",
              summary: "Virupaksha, the stone chariot and the bazaar, walked.",
              effort: "easy",
              minutes: 180,
            },
          ],
          wikidataId: "Q26732",
          kind: "culture",
          summary: "Temples, bazaars and a stone chariot spread over 4,000 hectares.",
          lat: 15.3350,
          lng: 76.4600,
          visitMinutes: 420,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Shadeless granite — go at dawn, and avoid April to June entirely.",
          collectibles: [
            {
              name: "Hampi site stamp",
              slug: "hampi-site-stamp",
              kind: "stamp",
              description: "Date stamp issued with the combined monument ticket.",
              whereToGet: "ASI ticket counter, Virupaksha temple entrance",
            },
          ],
        },
      ],
    },
    {
      name: "Madikeri",
      slug: "madikeri",
      region: "karnataka",
      wikidataId: "Q298416",
      summary: "Hill town in Kodagu — coffee estates, misty ridges and river valleys.",
      lat: 12.4244,
      lng: 75.7382,
      places: [
        {
          name: "Mysore Palace",
          slug: "mysore-palace",
          wikidataId: "Q456575",
          kind: "attraction",
          summary: "Indo-Saracenic royal palace, floodlit with 100,000 bulbs on Sunday evenings.",
          lat: 12.3052,
          lng: 76.6552,
          visitMinutes: 150,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote: "The Dasara illumination in autumn is the one to time for.",
          events: [
            {
              name: "Mysuru Dasara",
              slug: "mysuru-dasara",
              description:
                "Ten-day state festival ending in a procession of caparisoned elephants.",
              startMonth: 9,
              endMonth: 10,
            },
          ],
        },
      ],
    },
    {
      name: "Madurai",
      slug: "madurai",
      region: "tamil-nadu",
      wikidataId: "Q228405",
      summary: "Temple city on the Vaigai, continuously inhabited for over two millennia.",
      lat: 9.9252,
      lng: 78.1198,
      places: [
        {
          name: "Meenakshi Temple",
          slug: "meenakshi-temple",
          wikidataId: "Q1424358",
          kind: "culture",
          summary: "Fourteen gopurams covered in thousands of painted figures.",
          lat: 9.9195,
          lng: 78.1193,
          visitMinutes: 180,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Madurai is hot year-round; winter mornings are the bearable window.",
          collectibles: [
            {
              name: "Temple archana receipt",
              slug: "archana-receipt",
              kind: "stamp",
              description:
                "Printed receipt from an archana offering, naming the deity and the date.",
              whereToGet: "Ticket counters inside the east gopuram",
              cost: 100,
            },
          ],
        },
      ],
    },
    {
      name: "Mahabalipuram",
      slug: "mahabalipuram",
      region: "tamil-nadu",
      wikidataId: "Q208000",
      summary: "Pallava-era shore temples and rock-cut reliefs on the Coromandel coast.",
      lat: 12.6269,
      lng: 80.1927,
      places: [
        {
          name: "Shore Temple",
          slug: "shore-temple",
          kind: "culture",
          summary: "Eighth-century granite temple standing directly against the surf.",
          lat: 12.6161,
          lng: 80.1995,
          visitMinutes: 120,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "The northeast monsoon brings rain in October and November.",
        },
      ],
    },
    {
      name: "Shimla",
      slug: "shimla",
      region: "himachal-pradesh",
      wikidataId: "Q83786",
      summary: "Former summer capital of the Raj, strung along a Himalayan ridge.",
      lat: 31.1048,
      lng: 77.1734,
      places: [
        {
          name: "McLeod Ganj",
          slug: "mcleod-ganj",
          wikidataId: "Q3072050",
          kind: "culture",
          summary: "Tibetan quarter above Dharamshala, home of the Dalai Lama in exile.",
          lat: 32.2432,
          lng: 76.3235,
          visitMinutes: 300,
          bestMonths: [3, 4, 5, 9, 10, 11],
          seasonNote: "Heavy monsoon and winter snow both close mountain roads.",
        },
        {
          name: "Spiti Valley",
          slug: "spiti-valley",
          wikidataId: "Q2682249",
          kind: "nature",
          summary: "High cold desert of monasteries and glacial rivers above 3,000m.",
          lat: 32.2464,
          lng: 78.0349,
          visitMinutes: 480,
          bestMonths: [6, 7, 8, 9],
          seasonNote: "Roads in are only open roughly June to September; snowbound otherwise.",
        },
      ],
    },
    {
      name: "Rishikesh",
      slug: "rishikesh",
      region: "uttarakhand",
      wikidataId: "Q502141",
      summary: "Ganga town of ashrams and suspension bridges at the Himalayan foothills.",
      lat: 30.0869,
      lng: 78.2676,
      places: [
        {
          name: "Valley of Flowers National Park",
          slug: "valley-of-flowers",
          wikidataId: "Q605897",
          kind: "nature",
          summary: "Alpine meadow that flowers for a few weeks a year at 3,600m.",
          lat: 30.7283,
          lng: 79.6050,
          visitMinutes: 480,
          bestMonths: [7, 8],
          seasonNote: "Open June to October, but the bloom itself is July and August only.",
          events: [
            {
              name: "Peak bloom",
              slug: "valley-peak-bloom",
              description:
                "Several hundred alpine species flower together across the meadow.",
              startMonth: 7,
              endMonth: 8,
            },
          ],
        },
      ],
    },
    {
      name: "Leh",
      slug: "leh",
      region: "ladakh",
      wikidataId: "Q230818",
      summary: "Old Silk Road town below a ruined palace, thin air and a huge sky.",
      lat: 34.1526,
      lng: 77.5771,
      places: [
        {
          name: "Pangong Tso",
          slug: "pangong-tso",
          activities: [
            {
              name: "Day trip from Leh",
              slug: "day-trip",
              summary: "Long drive over Chang La, a few hours at the lake, back by dark.",
              effort: "moderate",
              minutes: 720,
            },
            {
              name: "Overnight camp by the lake",
              slug: "overnight-camp",
              summary: "Stay at the shore for sunset and sunrise on the water.",
              effort: "moderate",
              minutes: 1080,
              cost: 3500,
            },
          ],
          wikidataId: "Q1032254",
          kind: "nature",
          summary: "Endorheic lake at 4,350m that shifts between blue and green through the day.",
          lat: 33.7000,
          lng: 78.9000,
          visitMinutes: 420,
          bestMonths: [6, 7, 8, 9],
          seasonNote: "Passes close under snow; allow two days in Leh to acclimatise first.",
          collectibles: [
            {
              name: "Inner Line Permit",
              slug: "inner-line-permit",
              kind: "passport",
              description:
                "Permit required for the lake, stamped and carried for the whole journey.",
              whereToGet: "DC office in Leh, or online before arrival",
              cost: 600,
            },
          ],
        },
      ],
    },
    {
      name: "Amritsar",
      slug: "amritsar",
      region: "punjab",
      wikidataId: "Q48403",
      summary: "Sikh holy city built around a tank of water and a gilded temple.",
      lat: 31.6340,
      lng: 74.8723,
      places: [
        {
          name: "Golden Temple",
          slug: "golden-temple",
          activities: [
            {
              name: "Langar seva",
              slug: "langar-seva",
              summary: "Volunteer in the kitchen that feeds tens of thousands daily.",
              effort: "moderate",
              minutes: 120,
            },
            {
              name: "Parikrama and darshan",
              slug: "parikrama",
              summary: "Walk the marble circuit and queue for the inner sanctum.",
              effort: "easy",
              minutes: 150,
              bestTime: "Before dawn, when the marble is cool",
            },
          ],
          wikidataId: "Q180422",
          kind: "culture",
          summary:
            "Harmandir Sahib, where a free kitchen feeds tens of thousands every day.",
          lat: 31.6200,
          lng: 74.8765,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Open through the night; the marble is coolest before dawn.",
          collectibles: [
            {
              name: "Langar seva token",
              slug: "langar-seva",
              kind: "badge",
              description:
                "Given for volunteering in the community kitchen — washing dishes or rolling roti.",
              whereToGet: "Langar hall, east side of the complex",
            },
          ],
        },
      ],
    },
    {
      name: "Kolkata",
      slug: "kolkata",
      region: "west-bengal",
      wikidataId: "Q1348",
      summary: "Bengal's capital of coffee houses, trams and imperial architecture.",
      lat: 22.5726,
      lng: 88.3639,
      places: [
        {
          name: "Victoria Memorial Hall",
          slug: "victoria-memorial",
          wikidataId: "Q1356352",
          kind: "culture",
          summary: "White marble hall and museum set in sixty-four acres of garden.",
          lat: 22.5448,
          lng: 88.3426,
          visitMinutes: 150,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Kolkata is humid most of the year; winter is the pleasant season.",
          events: [
            {
              name: "Durga Puja",
              slug: "durga-puja",
              description:
                "The city fills with commissioned pandals and all-night crowds for five days.",
              startMonth: 9,
              endMonth: 10,
            },
          ],
        },
      ],
    },
    {
      name: "Darjeeling",
      slug: "darjeeling",
      region: "west-bengal",
      wikidataId: "Q1134759",
      summary: "Tea slopes below Kanchenjunga, reached by a narrow-gauge mountain railway.",
      lat: 27.0410,
      lng: 88.2663,
      places: [
        {
          name: "Darjeeling Himalayan Railway",
          slug: "darjeeling-railway",
          kind: "attraction",
          summary: "Two-foot-gauge 'toy train' climbing 2,000m through loops and switchbacks.",
          lat: 27.0416,
          lng: 88.2627,
          visitMinutes: 240,
          bestMonths: [3, 4, 5, 10, 11],
          seasonNote: "Clearest Kanchenjunga views come in autumn after the monsoon clears.",
        },
      ],
    },
    {
      name: "Gangtok",
      slug: "gangtok",
      region: "sikkim",
      wikidataId: "Q186141",
      summary: "Himalayan capital on a ridge, with monasteries and cloud below the road.",
      lat: 27.3314,
      lng: 88.6138,
      places: [
        {
          name: "Rumtek Monastery",
          slug: "rumtek-monastery",
          kind: "culture",
          summary: "Seat of the Karmapa in exile, above the valley outside town.",
          lat: 27.2880,
          lng: 88.5614,
          visitMinutes: 150,
          bestMonths: [3, 4, 5, 10, 11],
          seasonNote: "Landslides close roads during the monsoon, June to September.",
        },
      ],
    },
    {
      name: "Khajuraho",
      slug: "khajuraho",
      region: "madhya-pradesh",
      wikidataId: "Q167298",
      summary: "Chandela temple complex famous for its sculpted exteriors.",
      lat: 24.8318,
      lng: 79.9199,
      places: [
        {
          name: "Khajuraho Group of Monuments",
          slug: "khajuraho-monuments",
          wikidataId: "Q167298",
          kind: "culture",
          summary: "Twenty surviving temples of a group that once numbered eighty-five.",
          lat: 24.8318,
          lng: 79.9199,
          visitMinutes: 240,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote: "Central India bakes from March; winter is the only comfortable season.",
        },
      ],
    },
    {
      name: "Puri",
      slug: "puri",
      region: "odisha",
      summary: "Pilgrimage town on the Bay of Bengal, and gateway to the Sun Temple.",
      lat: 19.8135,
      lng: 85.8312,
      places: [
        {
          name: "Konark Sun Temple",
          slug: "konark-sun-temple",
          wikidataId: "Q752091",
          kind: "culture",
          summary: "Thirteenth-century temple built as the sun god's chariot, with stone wheels.",
          lat: 19.8876,
          lng: 86.0945,
          visitMinutes: 180,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Coastal humidity is heavy outside winter.",
        },
      ],
    },
    {
      name: "Ahmedabad",
      slug: "ahmedabad",
      region: "gujarat",
      wikidataId: "Q1070",
      summary: "Walled old city of carved wooden havelis, and India's first UNESCO city.",
      lat: 23.0225,
      lng: 72.5714,
      places: [
        {
          name: "Great Rann of Kutch",
          slug: "rann-of-kutch",
          wikidataId: "Q1118568",
          kind: "nature",
          summary: "Salt marsh that dries to a white plain stretching to the horizon.",
          lat: 23.8500,
          lng: 69.8500,
          visitMinutes: 360,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Underwater during the monsoon; the white season runs November to February.",
          events: [
            {
              name: "Rann Utsav",
              slug: "rann-utsav",
              description:
                "Tented festival on the salt flats with craft markets and full-moon nights.",
              startMonth: 11,
              endMonth: 2,
            },
          ],
        },
      ],
    },
    {
      name: "Jaisalmer",
      slug: "jaisalmer",
      region: "rajasthan",
      wikidataId: "Q242898",
      summary: "Yellow sandstone fort city rising out of the Thar desert.",
      lat: 26.9157,
      lng: 70.9083,
      places: [
        {
          name: "Jaisalmer Fort",
          slug: "jaisalmer-fort",
          kind: "attraction",
          summary: "One of the few forts in the world still lived in, with houses inside the walls.",
          lat: 26.9124,
          lng: 70.9127,
          visitMinutes: 240,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Desert summers exceed 45°C; winter nights are cold enough for a jacket.",
          collectibles: [
            {
              name: "Camel safari log",
              slug: "camel-safari-log",
              kind: "book",
              description:
                "Dated log from an overnight desert safari, signed by the guide.",
              whereToGet: "Licensed operators inside the fort gate",
              cost: 1500,
            },
          ],
        },
      ],
    },
    {
      name: "Shillong",
      slug: "shillong",
      region: "meghalaya",
      wikidataId: "Q207752",
      summary: "Hill capital of Meghalaya: pine ridges, colonial bones and a live music habit.",
      lat: 25.5788,
      lng: 91.8933,
      places: [
        {
          name: "Elephant Falls",
          slug: "elephant-falls",
          activities: [
            {
              name: "Walk all three tiers",
              slug: "three-tiers",
              summary: "Stepped path down to the lowest fall and back up.",
              effort: "moderate",
              minutes: 75,
              bestTime: "Early morning, before tour buses",
            },
            {
              name: "Top viewpoint only",
              slug: "top-viewpoint",
              summary: "Upper platform from the car park — no stairs.",
              effort: "easy",
              minutes: 25,
            },
          ],
          kind: "nature",
          summary: "Three-tier falls dropping through fern and moss a short drive from the city.",
          lat: 25.5497,
          lng: 91.8016,
          visitMinutes: 60,
          bestMonths: [10, 11, 3, 4],
          seasonNote: "Fullest right after the monsoon; steps get slippery in heavy rain.",
        },
        {
          name: "Mawlynnong",
          slug: "mawlynnong",
          activities: [
            {
              name: "Village walk and sky viewpoint",
              slug: "village-and-viewpoint",
              summary: "Lanes, bamboo dustbins and a climb to the bamboo sky walk.",
              effort: "moderate",
              minutes: 150,
              cost: 50,
            },
            {
              name: "Village walk only",
              slug: "village-walk",
              summary: "The swept lanes and church, skipping the climb.",
              effort: "easy",
              minutes: 60,
            },
          ],
          wikidataId: "Q6794437",
          kind: "hidden_gem",
          summary: "Khasi village known for its bamboo dustbins and swept lanes.",
          lat: 25.2011,
          lng: 91.9145,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 2, 3],
          seasonNote: "A long day trip from Shillong; leave early.",
          collectibles: [
            {
              name: "Khasi bamboo weave",
              slug: "khasi-bamboo-weave",
              kind: "souvenir",
              description:
                "Hand-woven bamboo baskets and mats made by village households.",
              whereToGet: "Village co-operative stalls on the main lane",
              cost: 350,
            },
          ],
        },
      ],
    },
    {
      name: "Cherrapunji",
      slug: "cherrapunji",
      region: "meghalaya",
      wikidataId: "Q211030",
      summary: "One of the wettest places on earth — gorges, waterfalls and living root bridges.",
      lat: 25.3000,
      lng: 91.7000,
      places: [
        {
          name: "Nohkalikai Falls",
          slug: "nohkalikai-falls",
          activities: [
            {
              name: "Viewpoint and cafe",
              slug: "viewpoint",
              summary: "Railed platform looking down the 340m drop.",
              effort: "easy",
              minutes: 60,
              cost: 20,
            },
          ],
          wikidataId: "Q3631209",
          kind: "nature",
          summary: "India's tallest plunge waterfall, dropping 340m into a green pool.",
          lat: 25.2760,
          lng: 91.6856,
          visitMinutes: 75,
          bestMonths: [9, 10, 11],
          seasonNote:
            "Thunderous just after monsoon; often swallowed by cloud between June and August.",
        },
        {
          name: "Living root bridges",
          slug: "living-root-bridges",
          activities: [
            {
              name: "Double-decker bridge trek",
              slug: "double-decker-trek",
              summary: "Roughly 3,000 steps down to Nongriat and back up again.",
              effort: "hard",
              minutes: 420,
              bestTime: "Start at dawn; the climb back is the hard half",
            },
            {
              name: "Single root bridge at Riwai",
              slug: "riwai-bridge",
              summary: "Short walk to a living bridge near Mawlynnong.",
              effort: "easy",
              minutes: 45,
              cost: 30,
            },
          ],
          wikidataId: "Q18349989",
          kind: "hidden_gem",
          summary:
            "Bridges grown over decades from the roots of rubber fig trees by Khasi communities.",
          lat: 25.2486,
          lng: 91.7126,
          visitMinutes: 300,
          bestMonths: [10, 11, 2, 3],
          seasonNote:
            "The double-decker bridge is roughly 3,000 steps down and back — start at dawn.",
          collectibles: [
            {
              name: "Root bridge trail stamp",
              slug: "root-bridge-stamp",
              kind: "stamp",
              description:
                "Trail register at the Nongriat guesthouse where trekkers sign in and stamp the date.",
              whereToGet: "Nongriat village guesthouse, at the foot of the descent",
            },
          ],
        },
      ],
    },
    {
      name: "Mumbai",
      slug: "mumbai",
      region: "maharashtra",
      wikidataId: "Q1156",
      summary: "India's loudest, fastest city — Art Deco seafronts, Gothic railways and island caves.",
      lat: 19.0760,
      lng: 72.8777,
      places: [
        {
          name: "Gateway of India",
          slug: "gateway-of-india",
          wikidataId: "Q864862",
          kind: "attraction",
          summary: "Basalt arch on the harbour, built to greet arriving ships.",
          lat: 18.9220,
          lng: 72.8347,
          visitMinutes: 60,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Avoid the June-September monsoon; winter evenings are the pleasant ones.",
        },
        {
          name: "Chhatrapati Shivaji Maharaj Terminus",
          slug: "cst-terminus",
          wikidataId: "Q235884",
          kind: "culture",
          summary: "Victorian Gothic railway station still running three million passengers a day.",
          lat: 18.9398,
          lng: 72.8355,
          visitMinutes: 45,
          seasonNote: "Floodlit after dark, which is when the facade photographs best.",
        },
        {
          name: "Elephanta Caves",
          slug: "elephanta-caves",
          wikidataId: "Q649384",
          kind: "culture",
          summary: "Rock-cut Shiva temples on an island an hour across the harbour.",
          lat: 18.9633,
          lng: 72.9315,
          visitMinutes: 240,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Ferries stop running in rough monsoon seas; the caves close on Mondays.",
        },
      ],
    },
    {
      name: "Delhi",
      slug: "delhi",
      region: "delhi",
      wikidataId: "Q1353",
      summary: "Seven historic cities layered into one: tombs, bazaars and broad colonial avenues.",
      lat: 28.6139,
      lng: 77.209,
      places: [
        {
          name: "Humayun's Tomb",
          slug: "humayuns-tomb",
          wikidataId: "Q189648",
          kind: "culture",
          summary: "The garden tomb that set the template the Taj Mahal would later perfect.",
          lat: 28.5933,
          lng: 77.2507,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Delhi is punishing April-September; winter mornings are cool and clear.",
        },
        {
          name: "Qutb Minar",
          slug: "qutb-minar",
          wikidataId: "Q187635",
          kind: "attraction",
          summary: "A 73m victory tower of banded sandstone, begun in 1199.",
          lat: 28.5245,
          lng: 77.1855,
          visitMinutes: 90,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Little shade on site — go early or late in the day.",
        },
        {
          name: "Chandni Chowk",
          slug: "chandni-chowk",
          wikidataId: "Q3236763",
          kind: "food",
          summary: "Old Delhi's dense market lanes: parathas, jalebi and centuries of trade.",
          lat: 28.6506,
          lng: 77.2303,
          visitMinutes: 150,
          seasonNote: "Busiest and best in the evening; many shops shut on Sundays.",
        },
      ],
    },
    {
      name: "Agra",
      slug: "agra",
      region: "uttar-pradesh",
      wikidataId: "Q42941",
      summary: "Mughal capital on the Yamuna, and home to the most famous building in the world.",
      lat: 27.1767,
      lng: 78.0081,
      places: [
        {
          name: "Taj Mahal",
          slug: "taj-mahal",
          wikidataId: "Q9141",
          kind: "attraction",
          summary: "White marble mausoleum built by Shah Jahan for Mumtaz Mahal.",
          lat: 27.1751,
          lng: 78.0421,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote:
            "Winter dawn is the classic view; the monument closes to visitors on Fridays.",
          collectibles: [
            {
              name: "Marble inlay coaster",
              slug: "marble-inlay",
              kind: "souvenir",
              description:
                "Pietra dura inlay in the same technique as the mausoleum, made by local artisan families.",
              whereToGet: "Government-approved emporiums near the east gate",
              cost: 600,
            },
          ],
        },
        {
          name: "Agra Fort",
          slug: "agra-fort",
          wikidataId: "Q171857",
          kind: "culture",
          summary: "Red sandstone fortress where Shah Jahan was imprisoned in view of the Taj.",
          lat: 27.1795,
          lng: 78.0211,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote: "Pair with a sunrise Taj visit — the fort is quieter mid-morning.",
        },
      ],
    },
    {
      name: "Jaipur",
      slug: "jaipur",
      region: "rajasthan",
      wikidataId: "Q66485",
      summary: "Rajasthan's pink city: hilltop forts, stepwells and painted facades.",
      lat: 26.9124,
      lng: 75.7873,
      places: [
        {
          name: "Amber Fort",
          slug: "amber-fort",
          wikidataId: "Q456817",
          kind: "attraction",
          summary: "Hilltop palace of mirrored halls above Maota lake.",
          lat: 26.9855,
          lng: 75.8513,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Steep approach; brutal in summer heat.",
        },
        {
          name: "Hawa Mahal",
          slug: "hawa-mahal",
          wikidataId: "Q836531",
          kind: "culture",
          summary: "Honeycomb facade of 953 windows, built so royal women could watch the street.",
          lat: 26.9239,
          lng: 75.8267,
          visitMinutes: 60,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "The facade faces east — morning light is the one to photograph.",
          events: [
            {
              name: "Teej festival",
              slug: "teej",
              description:
                "Monsoon festival with processions through the old city, when Jaipur dresses in green.",
              startMonth: 7,
              endMonth: 8,
            },
          ],
        },
      ],
    },
  ],
};

export default india;
