import type { SeedCountry } from "./types";

const india: SeedCountry = {
  code: "IN",
  name: "India",
  slug: "india",
  motif: "peacock",
  wikidataId: "Q668",
  emoji: "🇮🇳",
  regions: [
    { name: "Delhi", slug: "delhi", kind: "union territory", wikidataId: "Q1353" },
  { name: "Andhra Pradesh", slug: "andhra-pradesh", kind: "state", wikidataId: "Q1159" },
  { name: "Arunachal Pradesh", slug: "arunachal-pradesh", kind: "state", wikidataId: "Q1162" },
  { name: "Assam", slug: "assam", kind: "state", wikidataId: "Q1164" },
  { name: "Bihar", slug: "bihar", kind: "state", wikidataId: "Q1165" },
  { name: "Chhattisgarh", slug: "chhattisgarh", kind: "state", wikidataId: "Q1168" },
  { name: "Goa", slug: "goa", kind: "state", wikidataId: "Q1171" },
  { name: "Gujarat", slug: "gujarat", kind: "state", wikidataId: "Q1061" },
  { name: "Haryana", slug: "haryana", kind: "state", wikidataId: "Q1174" },
  { name: "Himachal Pradesh", slug: "himachal-pradesh", kind: "state", wikidataId: "Q1177" },
  { name: "Jharkhand", slug: "jharkhand", kind: "state", wikidataId: "Q1184" },
  { name: "Karnataka", slug: "karnataka", kind: "state", wikidataId: "Q1185" },
  { name: "Kerala", slug: "kerala", kind: "state", wikidataId: "Q1186" },
  { name: "Madhya Pradesh", slug: "madhya-pradesh", kind: "state", wikidataId: "Q1188" },
  { name: "Maharashtra", slug: "maharashtra", kind: "state", wikidataId: "Q1191" },
  { name: "Manipur", slug: "manipur", kind: "state", wikidataId: "Q1193" },
  { name: "Meghalaya", slug: "meghalaya", kind: "state", wikidataId: "Q1195" },
  { name: "Mizoram", slug: "mizoram", kind: "state", wikidataId: "Q1502" },
  { name: "Nagaland", slug: "nagaland", kind: "state", wikidataId: "Q1599" },
  { name: "Odisha", slug: "odisha", kind: "state", wikidataId: "Q22048" },
  { name: "Punjab", slug: "punjab", kind: "state", wikidataId: "Q22424" },
  { name: "Rajasthan", slug: "rajasthan", kind: "state", wikidataId: "Q1437" },
  { name: "Sikkim", slug: "sikkim", kind: "state", wikidataId: "Q1505" },
  { name: "Tamil Nadu", slug: "tamil-nadu", kind: "state", wikidataId: "Q1445" },
  { name: "Telangana", slug: "telangana", kind: "state", wikidataId: "Q677037" },
  { name: "Tripura", slug: "tripura", kind: "state", wikidataId: "Q1363" },
  { name: "Uttar Pradesh", slug: "uttar-pradesh", kind: "state", wikidataId: "Q1498" },
  { name: "Uttarakhand", slug: "uttarakhand", kind: "state", wikidataId: "Q1499" },
  { name: "West Bengal", slug: "west-bengal", kind: "state", wikidataId: "Q1356" },
  ],
  summary:
    "Mughal marble, painted palaces and food worth travelling for — India rewards the unhurried.",
  cities: [
    {
      name: "Shillong",
      slug: "shillong",
      region: "meghalaya",
      wikidataId: "Q207752",
      summary: "Hill capital of Meghalaya: pine ridges, colonial bones and a live music habit.",
      lat: 25.5788,
      lng: 91.8933,
      places: [
        {
          name: "Elephant Falls",
          slug: "elephant-falls",
          kind: "nature",
          summary: "Three-tier falls dropping through fern and moss a short drive from the city.",
          lat: 25.5497,
          lng: 91.8016,
          visitMinutes: 60,
          bestMonths: [10, 11, 3, 4],
          seasonNote: "Fullest right after the monsoon; steps get slippery in heavy rain.",
        },
        {
          name: "Mawlynnong",
          slug: "mawlynnong",
          wikidataId: "Q6794437",
          kind: "hidden_gem",
          summary: "Khasi village known for its bamboo dustbins and swept lanes.",
          lat: 25.2011,
          lng: 91.9145,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 2, 3],
          seasonNote: "A long day trip from Shillong; leave early.",
          collectibles: [
            {
              name: "Khasi bamboo weave",
              slug: "khasi-bamboo-weave",
              kind: "souvenir",
              description:
                "Hand-woven bamboo baskets and mats made by village households.",
              whereToGet: "Village co-operative stalls on the main lane",
              cost: 350,
            },
          ],
        },
      ],
    },
    {
      name: "Cherrapunji",
      slug: "cherrapunji",
      region: "meghalaya",
      wikidataId: "Q211030",
      summary: "One of the wettest places on earth — gorges, waterfalls and living root bridges.",
      lat: 25.3000,
      lng: 91.7000,
      places: [
        {
          name: "Nohkalikai Falls",
          slug: "nohkalikai-falls",
          wikidataId: "Q3631209",
          kind: "nature",
          summary: "India's tallest plunge waterfall, dropping 340m into a green pool.",
          lat: 25.2760,
          lng: 91.6856,
          visitMinutes: 75,
          bestMonths: [9, 10, 11],
          seasonNote:
            "Thunderous just after monsoon; often swallowed by cloud between June and August.",
        },
        {
          name: "Living root bridges",
          slug: "living-root-bridges",
          wikidataId: "Q18349989",
          kind: "hidden_gem",
          summary:
            "Bridges grown over decades from the roots of rubber fig trees by Khasi communities.",
          lat: 25.2486,
          lng: 91.7126,
          visitMinutes: 300,
          bestMonths: [10, 11, 2, 3],
          seasonNote:
            "The double-decker bridge is roughly 3,000 steps down and back — start at dawn.",
          collectibles: [
            {
              name: "Root bridge trail stamp",
              slug: "root-bridge-stamp",
              kind: "stamp",
              description:
                "Trail register at the Nongriat guesthouse where trekkers sign in and stamp the date.",
              whereToGet: "Nongriat village guesthouse, at the foot of the descent",
            },
          ],
        },
      ],
    },
    {
      name: "Mumbai",
      slug: "mumbai",
      region: "maharashtra",
      wikidataId: "Q1156",
      summary: "India's loudest, fastest city — Art Deco seafronts, Gothic railways and island caves.",
      lat: 19.0760,
      lng: 72.8777,
      places: [
        {
          name: "Gateway of India",
          slug: "gateway-of-india",
          wikidataId: "Q864862",
          kind: "attraction",
          summary: "Basalt arch on the harbour, built to greet arriving ships.",
          lat: 18.9220,
          lng: 72.8347,
          visitMinutes: 60,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Avoid the June-September monsoon; winter evenings are the pleasant ones.",
        },
        {
          name: "Chhatrapati Shivaji Maharaj Terminus",
          slug: "cst-terminus",
          wikidataId: "Q235884",
          kind: "culture",
          summary: "Victorian Gothic railway station still running three million passengers a day.",
          lat: 18.9398,
          lng: 72.8355,
          visitMinutes: 45,
          seasonNote: "Floodlit after dark, which is when the facade photographs best.",
        },
        {
          name: "Elephanta Caves",
          slug: "elephanta-caves",
          wikidataId: "Q649384",
          kind: "culture",
          summary: "Rock-cut Shiva temples on an island an hour across the harbour.",
          lat: 18.9633,
          lng: 72.9315,
          visitMinutes: 240,
          bestMonths: [11, 12, 1, 2],
          seasonNote: "Ferries stop running in rough monsoon seas; the caves close on Mondays.",
        },
      ],
    },
    {
      name: "Delhi",
      slug: "delhi",
      region: "delhi",
      wikidataId: "Q1353",
      summary: "Seven historic cities layered into one: tombs, bazaars and broad colonial avenues.",
      lat: 28.6139,
      lng: 77.209,
      places: [
        {
          name: "Humayun's Tomb",
          slug: "humayuns-tomb",
          wikidataId: "Q189648",
          kind: "culture",
          summary: "The garden tomb that set the template the Taj Mahal would later perfect.",
          lat: 28.5933,
          lng: 77.2507,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Delhi is punishing April-September; winter mornings are cool and clear.",
        },
        {
          name: "Qutb Minar",
          slug: "qutb-minar",
          wikidataId: "Q187635",
          kind: "attraction",
          summary: "A 73m victory tower of banded sandstone, begun in 1199.",
          lat: 28.5245,
          lng: 77.1855,
          visitMinutes: 90,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Little shade on site — go early or late in the day.",
        },
        {
          name: "Chandni Chowk",
          slug: "chandni-chowk",
          wikidataId: "Q3236763",
          kind: "food",
          summary: "Old Delhi's dense market lanes: parathas, jalebi and centuries of trade.",
          lat: 28.6506,
          lng: 77.2303,
          visitMinutes: 150,
          seasonNote: "Busiest and best in the evening; many shops shut on Sundays.",
        },
      ],
    },
    {
      name: "Agra",
      slug: "agra",
      region: "uttar-pradesh",
      wikidataId: "Q42941",
      summary: "Mughal capital on the Yamuna, and home to the most famous building in the world.",
      lat: 27.1767,
      lng: 78.0081,
      places: [
        {
          name: "Taj Mahal",
          slug: "taj-mahal",
          wikidataId: "Q9141",
          kind: "attraction",
          summary: "White marble mausoleum built by Shah Jahan for Mumtaz Mahal.",
          lat: 27.1751,
          lng: 78.0421,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote:
            "Winter dawn is the classic view; the monument closes to visitors on Fridays.",
          collectibles: [
            {
              name: "Marble inlay coaster",
              slug: "marble-inlay",
              kind: "souvenir",
              description:
                "Pietra dura inlay in the same technique as the mausoleum, made by local artisan families.",
              whereToGet: "Government-approved emporiums near the east gate",
              cost: 600,
            },
          ],
        },
        {
          name: "Agra Fort",
          slug: "agra-fort",
          wikidataId: "Q171857",
          kind: "culture",
          summary: "Red sandstone fortress where Shah Jahan was imprisoned in view of the Taj.",
          lat: 27.1795,
          lng: 78.0211,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote: "Pair with a sunrise Taj visit — the fort is quieter mid-morning.",
        },
      ],
    },
    {
      name: "Jaipur",
      slug: "jaipur",
      region: "rajasthan",
      wikidataId: "Q66485",
      summary: "Rajasthan's pink city: hilltop forts, stepwells and painted facades.",
      lat: 26.9124,
      lng: 75.7873,
      places: [
        {
          name: "Amber Fort",
          slug: "amber-fort",
          wikidataId: "Q456817",
          kind: "attraction",
          summary: "Hilltop palace of mirrored halls above Maota lake.",
          lat: 26.9855,
          lng: 75.8513,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Steep approach; brutal in summer heat.",
        },
        {
          name: "Hawa Mahal",
          slug: "hawa-mahal",
          wikidataId: "Q836531",
          kind: "culture",
          summary: "Honeycomb facade of 953 windows, built so royal women could watch the street.",
          lat: 26.9239,
          lng: 75.8267,
          visitMinutes: 60,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "The facade faces east — morning light is the one to photograph.",
          events: [
            {
              name: "Teej festival",
              slug: "teej",
              description:
                "Monsoon festival with processions through the old city, when Jaipur dresses in green.",
              startMonth: 7,
              endMonth: 8,
            },
          ],
        },
      ],
    },
  ],
};

export default india;
