import type { SeedCountry } from "./types";

const india: SeedCountry = {
  code: "IN",
  name: "India",
  slug: "india",
  motif: "peacock",
  wikidataId: "Q668",
  emoji: "🇮🇳",
  summary:
    "Mughal marble, painted palaces and food worth travelling for — India rewards the unhurried.",
  cities: [
    {
      name: "Delhi",
      slug: "delhi",
      wikidataId: "Q1353",
      summary: "Seven historic cities layered into one: tombs, bazaars and broad colonial avenues.",
      lat: 28.6139,
      lng: 77.209,
      places: [
        {
          name: "Humayun's Tomb",
          slug: "humayuns-tomb",
          wikidataId: "Q189648",
          kind: "culture",
          summary: "The garden tomb that set the template the Taj Mahal would later perfect.",
          lat: 28.5933,
          lng: 77.2507,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Delhi is punishing April-September; winter mornings are cool and clear.",
        },
        {
          name: "Qutb Minar",
          slug: "qutb-minar",
          wikidataId: "Q187635",
          kind: "attraction",
          summary: "A 73m victory tower of banded sandstone, begun in 1199.",
          lat: 28.5245,
          lng: 77.1855,
          visitMinutes: 90,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Little shade on site — go early or late in the day.",
        },
        {
          name: "Chandni Chowk",
          slug: "chandni-chowk",
          wikidataId: "Q3236763",
          kind: "food",
          summary: "Old Delhi's dense market lanes: parathas, jalebi and centuries of trade.",
          lat: 28.6506,
          lng: 77.2303,
          visitMinutes: 150,
          seasonNote: "Busiest and best in the evening; many shops shut on Sundays.",
        },
      ],
    },
    {
      name: "Agra",
      slug: "agra",
      wikidataId: "Q42941",
      summary: "Mughal capital on the Yamuna, and home to the most famous building in the world.",
      lat: 27.1767,
      lng: 78.0081,
      places: [
        {
          name: "Taj Mahal",
          slug: "taj-mahal",
          wikidataId: "Q9141",
          kind: "attraction",
          summary: "White marble mausoleum built by Shah Jahan for Mumtaz Mahal.",
          lat: 27.1751,
          lng: 78.0421,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote:
            "Winter dawn is the classic view; the monument closes to visitors on Fridays.",
          collectibles: [
            {
              name: "Marble inlay coaster",
              slug: "marble-inlay",
              kind: "souvenir",
              description:
                "Pietra dura inlay in the same technique as the mausoleum, made by local artisan families.",
              whereToGet: "Government-approved emporiums near the east gate",
              cost: 600,
            },
          ],
        },
        {
          name: "Agra Fort",
          slug: "agra-fort",
          wikidataId: "Q171857",
          kind: "culture",
          summary: "Red sandstone fortress where Shah Jahan was imprisoned in view of the Taj.",
          lat: 27.1795,
          lng: 78.0211,
          visitMinutes: 120,
          bestMonths: [10, 11, 12, 1, 2],
          seasonNote: "Pair with a sunrise Taj visit — the fort is quieter mid-morning.",
        },
      ],
    },
    {
      name: "Jaipur",
      slug: "jaipur",
      wikidataId: "Q66485",
      summary: "Rajasthan's pink city: hilltop forts, stepwells and painted facades.",
      lat: 26.9124,
      lng: 75.7873,
      places: [
        {
          name: "Amber Fort",
          slug: "amber-fort",
          wikidataId: "Q456817",
          kind: "attraction",
          summary: "Hilltop palace of mirrored halls above Maota lake.",
          lat: 26.9855,
          lng: 75.8513,
          visitMinutes: 180,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "Steep approach; brutal in summer heat.",
        },
        {
          name: "Hawa Mahal",
          slug: "hawa-mahal",
          wikidataId: "Q836531",
          kind: "culture",
          summary: "Honeycomb facade of 953 windows, built so royal women could watch the street.",
          lat: 26.9239,
          lng: 75.8267,
          visitMinutes: 60,
          bestMonths: [10, 11, 12, 1, 2, 3],
          seasonNote: "The facade faces east — morning light is the one to photograph.",
          events: [
            {
              name: "Teej festival",
              slug: "teej",
              description:
                "Monsoon festival with processions through the old city, when Jaipur dresses in green.",
              startMonth: 7,
              endMonth: 8,
            },
          ],
        },
      ],
    },
  ],
};

export default india;
