import type { SeedCountry } from "./types";

const italy: SeedCountry = {
  code: "IT",
  name: "Italy",
  slug: "italy",
  motif: "laurel",
  wikidataId: "Q38",
  emoji: "🇮🇹",
  regions: [
    { name: "Lazio", slug: "lazio", kind: "region", wikidataId: "Q1282" },
    { name: "Tuscany", slug: "tuscany", kind: "region", wikidataId: "Q1273" },
    { name: "Veneto", slug: "veneto", kind: "region", wikidataId: "Q1243" },
  ],
  summary:
    "Ruins, Renaissance and long lunches — Italy stacks three thousand years into walkable cities.",
  cities: [
    {
      name: "Rome",
      slug: "rome",
      region: "lazio",
      wikidataId: "Q220",
      summary: "Layer upon layer of empire, still in daily use as a capital city.",
      lat: 41.9028,
      lng: 12.4964,
      places: [
        {
          name: "Colosseum",
          slug: "colosseum",
          wikidataId: "Q10285",
          kind: "attraction",
          summary: "The largest amphitheatre ever built, opened in AD 80.",
          lat: 41.8902,
          lng: 12.4922,
          visitMinutes: 150,
          bestMonths: [4, 5, 9, 10],
          seasonNote: "August is hot and packed; spring and autumn are far kinder.",
          collectibles: [
            {
              name: "Roma Pass",
              slug: "roma-pass",
              kind: "passport",
              description:
                "Transport and museum card that also skips the main ticket queue at several sites.",
              whereToGet: "Tourist information points and participating museums",
              cost: 3300,
            },
          ],
        },
        {
          name: "Pantheon",
          slug: "pantheon",
          wikidataId: "Q99309",
          kind: "culture",
          summary: "Still the world's largest unreinforced concrete dome, nearly 1900 years on.",
          lat: 41.8986,
          lng: 12.4769,
          visitMinutes: 60,
          seasonNote: "Indoors and central — a reliable stop in rain or heat.",
        },
        {
          name: "Roman Forum",
          slug: "roman-forum",
          wikidataId: "Q180212",
          kind: "culture",
          summary: "The civic heart of the ancient city, now a field of columns and basilicas.",
          lat: 41.8925,
          lng: 12.4853,
          visitMinutes: 120,
          bestMonths: [4, 5, 9, 10],
          seasonNote: "Almost no shade; avoid the middle of a summer day.",
        },
        {
          name: "Trevi Fountain",
          slug: "trevi-fountain",
          wikidataId: "Q185382",
          kind: "hidden_gem",
          summary: "Baroque fountain at the end of an aqueduct still fed by its ancient source.",
          lat: 41.9009,
          lng: 12.4833,
          visitMinutes: 30,
          seasonNote: "Go before 8am or after midnight to see it without a crowd.",
        },
      ],
    },
    {
      name: "Florence",
      slug: "florence",
      region: "tuscany",
      wikidataId: "Q2044",
      summary: "The Renaissance in one compact, walkable centre.",
      lat: 43.7696,
      lng: 11.2558,
      places: [
        {
          name: "Uffizi Gallery",
          slug: "uffizi",
          wikidataId: "Q51252",
          kind: "culture",
          summary: "Botticelli, Leonardo and Caravaggio in the Medici's own collection.",
          lat: 43.7678,
          lng: 11.2553,
          visitMinutes: 210,
          bestMonths: [3, 4, 5, 9, 10, 11],
          seasonNote: "Book a timed slot; walk-up queues run for hours in summer.",
        },
        {
          name: "Florence Cathedral",
          slug: "florence-cathedral",
          wikidataId: "Q191739",
          kind: "attraction",
          summary: "Brunelleschi's dome, still the largest masonry dome in the world.",
          lat: 43.7731,
          lng: 11.256,
          visitMinutes: 120,
          bestMonths: [3, 4, 5, 9, 10],
          seasonNote: "The 463-step dome climb is airless in high summer.",
        },
        {
          name: "Ponte Vecchio",
          slug: "ponte-vecchio",
          wikidataId: "Q208633",
          kind: "hidden_gem",
          summary: "Medieval bridge still lined with goldsmiths, as it has been since 1593.",
          lat: 43.768,
          lng: 11.2531,
          visitMinutes: 45,
          seasonNote: "Best at first light, when the shops are shuttered and the bridge is empty.",
        },
      ],
    },
    {
      name: "Venice",
      slug: "venice",
      region: "veneto",
      wikidataId: "Q641",
      summary: "A city built on 118 islands, with canals where the streets should be.",
      lat: 45.4408,
      lng: 12.3155,
      places: [
        {
          name: "St Mark's Basilica",
          slug: "st-marks-basilica",
          wikidataId: "Q172988",
          kind: "culture",
          summary: "Byzantine domes and eight thousand square metres of gold mosaic.",
          lat: 45.4345,
          lng: 12.3397,
          visitMinutes: 90,
          bestMonths: [4, 5, 6, 9, 10],
          seasonNote:
            "Acqua alta floods the square most often between October and January.",
        },
        {
          name: "Doge's Palace",
          slug: "doges-palace",
          wikidataId: "Q189883",
          kind: "culture",
          summary: "Seat of the Venetian Republic, linked to its prison by the Bridge of Sighs.",
          lat: 45.4337,
          lng: 12.3403,
          visitMinutes: 120,
          bestMonths: [4, 5, 6, 9, 10],
          seasonNote: "Pair with the basilica next door; both sit on Piazza San Marco.",
          events: [
            {
              name: "Carnival of Venice",
              slug: "carnevale",
              description:
                "Masked processions and balls across the city in the weeks before Lent.",
              startMonth: 2,
              endMonth: 3,
            },
          ],
        },
      ],
    },
  ],
};

export default italy;
